Update IDLE2HTML.py
"Export to HTML" creates an empty HTML file due to:
AttributeError: module 'cgi' has no attribute 'escape'
cgi.escape has been deprecated since Python 3.2 and has been removed in Python 3.8 (https://docs.python.org/3.7/library/cgi.html#cgi.escape)